# values.yaml
# Default values for app-of-apps
# This file can be used to override default values in the application templates

# Repository configuration
repository:
  url: "https://github.com/arthurzar/Estudos-ArgoCD.git"
  targetRevision: feat/day2

# ArgoCD configuration
argocd:
  giropops-senhas:
    enabled: true
  random-logger:
    enabled: true
  namespace: argocd
  project: default

# Sync policy configuration
syncPolicy:
  automated:
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
